import React from 'react';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import App from './App.jsx';
import { applyPreset } from './presets.js';
beforeEach(() => { localStorage.clear(); applyPreset('Glass clean'); });
afterEach(cleanup);
const open = () => { const button = screen.getByRole('button', {name: 'Library'}); button.focus(); fireEvent.click(button); return screen.getByRole('dialog'); };
describe('library preview', () => {
  it('loads a saved header rig, preserves listening levels and includes it in arrow stepping', async () => {
    localStorage.setItem('cassian-preview-rigs',JSON.stringify([{id:'one',name:'Saved clean',parameters:{DRIVE_GAIN:3}},{id:'two',name:'Saved lead',parameters:{DRIVE_GAIN:8}}]));
    render(<App/>); const preset=screen.getByRole('combobox',{name:'Preset'});
    await within(preset).findByRole('option',{name:'Saved clean'});
    fireEvent.change(screen.getByRole('slider',{name:'Master'}),{target:{value:'-24'}});
    fireEvent.change(preset,{target:{value:'one'}});
    expect(screen.getByRole('slider',{name:'Drive'}).value).toBe('3');
    expect(screen.getByRole('slider',{name:'Master'}).value).toBe('-24');
    fireEvent.click(screen.getByRole('button',{name:'Next preset'}));
    expect(screen.getByRole('slider',{name:'Drive'}).value).toBe('8');
    expect(document.querySelector('.preset-name').textContent).toBe('Saved lead');
  });
  it('filters complete starters and keeps listening controls when previewing a clean rig', async () => {
    render(<App/>); fireEvent.change(screen.getByRole('slider', {name: 'Master'}), {target: {value: '-28'}});
    const dialog = open(); fireEvent.click(within(dialog).getByRole('button', {name: 'Presets'}));
    fireEvent.change(within(dialog).getByRole('combobox', {name: 'Library rig type'}), {target: {value: 'starter'}});
    fireEvent.change(within(dialog).getByRole('combobox', {name: 'Library style'}), {target: {value: 'jazz'}});
    fireEvent.change(within(dialog).getByRole('combobox', {name: 'Library gain'}), {target: {value: 'clean'}});
    expect(within(dialog).queryByText('Modern Metalcore')).toBeNull(); expect(within(dialog).queryByText('Glass clean')).toBeNull();
    expect(within(dialog).getByText('Prism Clean')).toBeTruthy();
    expect(within(dialog).getByRole('status').textContent).toMatch(/^4 of \d+ rigs and starting points$/);
    fireEvent.click(within(within(dialog).getByText('Warm Jazz').closest('article')).getByRole('button', {name: 'Use'}));
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull());
    const bar = within(screen.getByRole('region', {name: 'Current complete rig'})); expect(bar.getByText('Warm Jazz')).toBeTruthy(); expect(bar.getByText('STARTER RIG')).toBeTruthy(); expect(bar.queryByText('Edited')).toBeNull();
    expect(screen.getByRole('slider', {name: 'Master'}).value).toBe('-28');
    fireEvent.click(bar.getByRole('button', {name: 'Save rig'})); expect(screen.getByRole('dialog', {name: 'Save complete rig'})).toBeTruthy();
  });
  it('searches built-in amps, remembers favorites, and keeps keyboard focus in the dialog', async () => {
    render(<App/>); let dialog = open();
    const close = within(dialog).getByRole('button', {name: 'Close library'});
    expect(document.activeElement).toBe(close);
    fireEvent.keyDown(close, {key: 'Tab', shiftKey: true});
    expect(document.activeElement).toBe(within(dialog).getByRole('textbox', {name: 'Rig name'}));
    fireEvent.change(within(dialog).getByRole('textbox', {name: 'Search library'}), {target: {value: 'jazz'}});
    expect(within(dialog).queryByText('Ferrum')).toBeNull();
    fireEvent.click(within(dialog).getByRole('button', {name: 'Favorite Lumen'}));
    await waitFor(() => expect(within(dialog).getByRole('button', {name: 'Favorite Lumen'}).getAttribute('aria-pressed')).toBe('true'));
    fireEvent.keyDown(dialog, {key: 'Escape'});
    expect(document.activeElement).toBe(screen.getByRole('button', {name: 'Library'}));
    dialog = open(); fireEvent.click(within(dialog).getByRole('checkbox', {name: 'Favorites'}));
    expect(within(dialog).getByText('Lumen')).toBeTruthy();
    expect(within(dialog).queryByText('Ferrum')).toBeNull();
  });
  it('saves preview control settings without changing listening volume on recall', async () => {
    render(<App/>);
    fireEvent.change(screen.getByRole('slider', {name: 'Drive'}), {target: {value: '5'}});
    let dialog = open();
    fireEvent.change(within(dialog).getByRole('textbox', {name: 'Rig name'}), {target: {value: 'Test lead'}});
    fireEvent.click(within(dialog).getByRole('button', {name: 'Save current rig'}));
    await within(dialog).findByText('Test lead');
    fireEvent.click(within(dialog).getByRole('button', {name: 'Close library'}));
    fireEvent.change(screen.getByRole('slider', {name: 'Drive'}), {target: {value: '12'}});
    fireEvent.change(screen.getByRole('slider', {name: 'Master'}), {target: {value: '-28'}});
    dialog = open(); fireEvent.click(within(dialog).getByRole('button', {name: 'Presets'}));
    fireEvent.click(within((await within(dialog).findByText('Test lead')).closest('article')).getByRole('button', {name: 'Use'}));
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull());
    expect(screen.getByRole('slider', {name: 'Drive'}).value).toBe('5');
    expect(screen.getByRole('slider', {name: 'Master'}).value).toBe('-28');
  });
  it('offers a neutral nylon path with electric simulation and cabinet disabled', async () => {
    render(<App/>); const dialog = open();
    fireEvent.click(within(within(dialog).getByText('Natural DI').closest('article')).getByRole('button', {name: 'Use'}));
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull());
    expect(screen.getAllByText('Natural DI').length).toBeGreaterThan(0);
    expect(screen.getByRole('button', {name: 'Channel'}).disabled).toBe(true);
    fireEvent.click(screen.getByRole('tab', {name: 'Board'}));
    fireEvent.click(screen.getByRole('tab', {name: 'Effects'}));
    expect(screen.getByRole('slider', {name: 'Piezo'}).getAttribute('aria-valuetext')).toBe('Off');
    fireEvent.click(screen.getByRole('tab', {name: 'Cab'}));
    expect(screen.getByRole('combobox', {name: 'Cabinet mode'}).value).toBe('3');
  });
  it('organizes a saved rig, keeps unsaved tone edits, and duplicates its saved settings', async () => {
    localStorage.setItem('cassian-preview-rigs', JSON.stringify([{id:'saved',name:'My clean',parameters:{DRIVE_GAIN:5}}]));
    render(<App/>); let dialog=open(); fireEvent.click(within(dialog).getByRole('button',{name:'Presets'}));
    fireEvent.click(within((await within(dialog).findByText('My clean')).closest('article')).getByRole('button',{name:'Use'}));
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull());
    fireEvent.change(screen.getByRole('slider',{name:'Drive'}),{target:{value:'12'}});
    dialog=open(); fireEvent.click(within(dialog).getByRole('button',{name:'Presets'}));
    fireEvent.click(await within(dialog).findByText('My clean'));
    fireEvent.change(within(dialog).getByLabelText('Saved rig name'),{target:{value:'Jazz rehearsal'}});
    fireEvent.change(within(dialog).getByLabelText('Rig styles (comma separated)'),{target:{value:'Jazz, clean, JAZZ'}});
    fireEvent.change(within(dialog).getByLabelText('Rig gain'),{target:{value:'clean'}});
    fireEvent.change(within(dialog).getByLabelText('Rig tags'),{target:{value:'neck pickup'}});
    fireEvent.change(within(dialog).getByLabelText('Rig notes'),{target:{value:'Warm backing track tone'}});
    fireEvent.click(within(dialog).getByRole('button',{name:'Save rig metadata'}));
    await waitFor(() => expect(within(dialog).getByRole('button',{name:'Duplicate rig Jazz rehearsal'})).toBeTruthy());
    fireEvent.click(within(dialog).getByRole('button',{name:'Duplicate rig Jazz rehearsal'}));
    await within(dialog).findByText('Jazz rehearsal copy');
    const saved=JSON.parse(localStorage.getItem('cassian-preview-rigs'));
    expect(saved).toHaveLength(2); expect(saved[0].styles).toBe('jazz, clean'); expect(saved[1].parameters.DRIVE_GAIN).toBe(5);
    expect(saved[1].id).not.toBe('saved'); expect(saved[1].favorite).toBe(false); expect(saved[1].notes).toBe('Warm backing track tone');
    fireEvent.change(within(dialog).getByLabelText('Library style'),{target:{value:'jazz'}});
    fireEvent.change(within(dialog).getByLabelText('Library ownership'),{target:{value:'User'}});
    fireEvent.change(within(dialog).getByLabelText('Search library'),{target:{value:'neck pickup'}});
    expect(within(dialog).getByText('Jazz rehearsal copy')).toBeTruthy();
    fireEvent.click(within(dialog).getByRole('button',{name:'Close library'}));
    const bar=within(screen.getByRole('region',{name:'Current complete rig'}));
    expect(bar.getByText('Jazz rehearsal')).toBeTruthy(); expect(bar.getByText('Edited')).toBeTruthy();
    expect(screen.getByRole('slider',{name:'Drive'}).value).toBe('12');
    fireEvent.click(bar.getByRole('button',{name:'Save rig'}));
    await waitFor(() => expect(JSON.parse(localStorage.getItem('cassian-preview-rigs')).find(r=>r.id==='saved').parameters.DRIVE_GAIN).toBe(12));
    expect(JSON.parse(localStorage.getItem('cassian-preview-rigs')).find(r=>r.id==='saved').notes).toBe('Warm backing track tone');
  });
});
