import React from 'react';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import App from './App.jsx';
import { applyPreset } from './presets.js';
import { setParameter, readParameter } from './parameterState.js';
beforeEach(() => { localStorage.clear(); applyPreset('Glass clean'); setParameter('GUITAR_MIX_LEVEL', 0); setParameter('GUITAR_MIX_FOCUS', 0); });
afterEach(cleanup);
const view = name => fireEvent.click(screen.getByRole('tab', {name}));
const bar = () => within(screen.getByRole('region', {name: 'Current complete rig'}));
describe('workspace navigation and complete rig bar', () => {
  it('opens help without changing the playing workspace and returns keyboard focus', () => {
    render(<App/>); view('Takes'); const help=screen.getByRole('button',{name:'Help & setup'});help.focus();fireEvent.click(help);
    const dialog=screen.getByRole('dialog',{name:'Help & setup'});
    expect(screen.getByRole('tab',{name:'Takes'}).getAttribute('aria-selected')).toBe('true');
    expect(within(dialog).getByText(/This browser is a preview/)).toBeTruthy();
    expect(within(dialog).getByRole('button',{name:'Copy support report'}).disabled).toBe(true);
    const close=within(dialog).getByRole('button',{name:'Close help & setup'});
    fireEvent.keyDown(close,{key:'Tab',shiftKey:true});
    expect(document.activeElement).toBe(within(dialog).getByRole('link',{name:'License'}));
    fireEvent.keyDown(document.activeElement,{key:'Tab'});expect(document.activeElement).toBe(close);
    fireEvent.keyDown(dialog,{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();expect(document.activeElement).toBe(help);
  });
  it('keeps one destination active with keyboard access and gives Practice/Takes a compact amp', () => {
    render(<App/>);
    const workspace = within(screen.getByRole('tablist', {name: 'Workspace'}));
    expect(workspace.getAllByRole('tab').map(x => x.textContent)).toEqual(['Tone', 'Board', 'Practice', 'Takes']);
    expect(within(screen.getByRole('tablist', {name: 'Signal chain'})).getAllByRole('tab').map(x => x.getAttribute('aria-label'))).toEqual(['Amp', 'Cab']);
    fireEvent.keyDown(workspace.getByRole('tab', {name: 'Tone'}), {key: 'ArrowRight'});
    expect(document.activeElement).toBe(workspace.getByRole('tab', {name: 'Board'}));
    fireEvent.keyDown(document.activeElement, {key: 'ArrowRight'});
    expect(screen.getByRole('region', {name: 'Compact amplifier'})).toBeTruthy();
    expect(screen.queryByRole('region', {name: 'Amplifier'})).toBeNull();
    expect(screen.getByRole('region', {name: 'Practice and recording'})).toBeTruthy();
    fireEvent.click(screen.getByRole('button', {name: 'Take library'}));
    expect(screen.getByRole('region', {name: 'Take library'})).toBeTruthy();
    expect(screen.queryByRole('region', {name: 'Practice and recording'})).toBeNull();
    expect(workspace.getAllByRole('tab').filter(x => x.getAttribute('aria-selected') === 'true')).toHaveLength(1);
    fireEvent.keyDown(workspace.getByRole('tab', {name: 'Takes'}), {key: 'Home'});
    expect(screen.getByRole('region', {name: 'Amplifier'})).toBeTruthy();
  });
  it('opens utilities without changing destination, traps focus, and returns to their trigger', () => {
    render(<App/>); view('Practice');
    const mix = screen.getByRole('button', {name: 'Mix'}); mix.focus(); fireEvent.click(mix);
    const dialog = screen.getByRole('dialog', {name: 'Play along mix'}), close = within(dialog).getByRole('button', {name: 'Close play along mix'});
    expect(document.activeElement).toBe(close);
    fireEvent.keyDown(close, {key: 'Tab', shiftKey: true});
    expect(dialog.contains(document.activeElement)).toBe(true); expect(document.activeElement).not.toBe(close);
    expect(screen.getByRole('tab', {name: 'Practice'}).getAttribute('aria-selected')).toBe('true');
    fireEvent.keyDown(dialog, {key: 'Escape'});
    expect(screen.queryByRole('dialog')).toBeNull(); expect(document.activeElement).toBe(mix);
    fireEvent.click(screen.getByRole('button', {name: 'Performance'}));
    expect(screen.getByRole('dialog', {name: 'Performance settings'})).toBeTruthy();
  });
  it('names saved preview rigs, tracks tone edits across views, and excludes listening controls from edits/recall', () => {
    render(<App/>); fireEvent.click(bar().getByRole('button', {name: 'Save rig as'}));
    const dialog = screen.getByRole('dialog', {name: 'Save complete rig'});
    fireEvent.change(within(dialog).getByRole('textbox', {name: 'Rig name'}), {target: {value: 'My clean'}});
    fireEvent.click(within(dialog).getByRole('button', {name: 'Save complete rig'}));
    expect(screen.queryByRole('dialog')).toBeNull(); expect(bar().getByText('My clean')).toBeTruthy();
    setParameter('GUITAR_MIX_LEVEL', 4); setParameter('GUITAR_MIX_FOCUS', 55); setParameter('MASTER_VOL', -25);
    view('Practice'); expect(bar().queryByText('Edited')).toBeNull();
    fireEvent.change(screen.getByRole('slider', {name: 'Drive'}), {target: {value: '8'}});
    expect(bar().getByText('Edited')).toBeTruthy();
    fireEvent.click(bar().getByRole('button', {name: 'Save rig'})); expect(bar().queryByText('Edited')).toBeNull();
    fireEvent.click(bar().getByRole('button', {name: 'A/B compare'}));
    fireEvent.change(screen.getByRole('slider', {name: 'Drive'}), {target: {value: '12'}});
    fireEvent.click(bar().getByRole('button', {name: 'A/B compare'}));
    expect(screen.getByRole('slider', {name: 'Drive'}).value).toBe('8'); expect(bar().getByText('My clean')).toBeTruthy();
    expect(readParameter('GUITAR_MIX_LEVEL')).toBe(4); expect(readParameter('GUITAR_MIX_FOCUS')).toBe(55);
    expect(readParameter('MASTER_VOL')).toBe(-25);
  });
});
