export const parameters = [
  ['INPUT_GAIN', 'Input', -24, 24, 0, 'dB'],
  ['GATE_THRESH', 'Noise gate', -80, 0, -60, 'dB'],
  ['DRIVE_GAIN', 'Drive', 0, 24, 0, 'dB'],
  ['AMP_BASS', 'Bass', -12, 12, 0, 'dB'],
  ['AMP_MID', 'Middle', -12, 12, 0, 'dB'],
  ['AMP_TREBLE', 'Treble', -12, 12, 0, 'dB'],
  ['AMP_OUT', 'Output', -24, 12, 0, 'dB'],
  ['DELAY_TIME', 'Time', 40, 1000, 320, 'ms'],
  ['DELAY_MIX', 'Mix', 0, 100, 0, '%'],
  ['REVERB_MIX', 'Space', 0, 100, 12, '%'],
  ['MASTER_VOL', 'Master', -60, 6, -12, 'dB'],
  ['AMP_CLEAN', 'Clean channel', 0, 1, 0, ''],
  ['TIGHT', 'Tight', 20, 180, 20, 'Hz'],
  ['PRESENCE', 'Presence', -6, 6, 0, 'dB'],
  ['CLEAN_COMP', 'Compression', 0, 100, 35, '%'],
  ['HIGH_CUT', 'High cut', 3000, 20000, 20000, 'Hz'],
  ['DELAY_WIDTH', 'Width', 0, 100, 0, '%'],
  ['REVERB_SIZE', 'Room', 0, 100, 60, '%'],
  ['GATE_ON', 'Gate enabled', 0, 1, 1, ''],
  ['GATE_RELEASE', 'Release', 40, 500, 140, 'ms'],
  ['PEDAL_ON', 'Pedal enabled', 0, 1, 0, ''],
  ['DYN_RES_ON', 'Dynamic resonance', 0, 1, 0, ''],
  ['DYN_RES_AMOUNT', 'Chug cut', 0, 100, 50, '%'],
  ['CHUG_ATTACK', 'Pick attack', 0, 100, 0, '%'],
  ['THICKEN_ON', 'Sub-synthesis', 0, 1, 0, ''],
  ['THICKEN_MIX', 'Sub mix', 0, 100, 30, '%'],
  ['PIEZO_ON', 'Piezo resonator', 0, 1, 0, ''],
  ['PIEZO_BLEND', 'Piezo sparkle', 0, 100, 40, '%'],
  ['MICRO_DELAY', 'Micro-delay', 0, 1.0, 0.0, 'ms'],
].map(([id, label, min, max, initial, unit]) => ({ id, label, min, max, initial, unit }));
export const byId = Object.fromEntries(parameters.map(p => [p.id, p]));
